name: Snake GIF

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake GIF
        uses: Platane/snk@v3
        with:
          github_user: 'isabellamarques1824' # Substitua pelo seu nome de usuário
          gif: true
          svg: false
          transparent: true
